language: ruby

services:
  - postgresql

rvm:
  - 2.7.1

addons:
  chrome: stable

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

env:
  # DON'T DO THIS. DO NOT COMMIT YOUR MASTER KEY TO THE SOURCE CODE.
  # Ref: https://docs.travis-ci.com/user/encryption-keys/
  - RAILS_MASTER_KEY=02a9ea770b4985659e8ce92699f218dc

before_install:
  - nvm install 12
  - node -v
  - npm i -g yarn@^1.21.1
  - yarn
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

before_script:
  - psql -c 'create database "ruby2_rails6_bootstrap_heroku_test";' -U postgres
